const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
const APPLY_THEME = 'APPLY_THEME';
const RELOAD_THEMES = 'RELOAD_THEMES';
const THEMES = 'THEMES';
const THEME_APPLIED = 'THEME_APPLIED';

export { TOGGLE_FAVORITE, APPLY_THEME, RELOAD_THEMES, THEMES, THEME_APPLIED };
