const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
const APPLY_THEME = 'APPLY_THEME';
const RELOAD_THEMES = 'RELOAD_THEMES';
const THEMES = 'THEMES';
const THEME_APPLIED = 'THEME_APPLIED';
const CLEAR_LOG = 'CLEAR_LOG';
const APPEND_LOG = 'APPEND_LOG';
const LOG_UPDATED = 'LOG_UPDATED';

export {
  TOGGLE_FAVORITE,
  APPLY_THEME,
  RELOAD_THEMES,
  THEMES,
  THEME_APPLIED,
  CLEAR_LOG,
  APPEND_LOG,
  LOG_UPDATED,
};
