const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
const APPLY_THEME = 'APPLY_THEME';
const RELOAD_THEMES = 'RELOAD_THEMES';
const THEME_PROGRESS = 'THEME_PROGRESS';
const THEMES = 'THEMES';
const THEME_APPLIED = 'THEME_APPLIED';
const CLEAR_LOG = 'CLEAR_LOG';
const APPEND_LOG = 'APPEND_LOG';
const LOG_UPDATED = 'LOG_UPDATED';
const SELECT_NODE = 'SELECT_NODE';
const FILE_NAME = 'FILE_NAME';
const GET_FILE_NAME = 'GET_FILE_NAME';
const GET_LOCAL_VARIABLES = 'GET_LOCAL_VARIABLES';
const LOCAL_VARIABLES = 'LOCAL_VARIABLES';
const SEARCH_NODES_WITH_VARIABLE = 'SEARCH_NODES_WITH_VARIABLE';
const NODES_WITH_VARIABLE = 'NODES_WITH_VARIABLE';
const APPLY_ACCENT_STYLING = 'APPLY_ACCENT_STYLING';
const CLEAR_ACCENT_STYLING = 'CLEAR_ACCENT_STYLING';
const ACCENT_STYLING_APPLIED = 'ACCENT_STYLING_APPLIED';

export {
  TOGGLE_FAVORITE,
  APPLY_THEME,
  RELOAD_THEMES,
  THEMES,
  THEME_APPLIED,
  CLEAR_LOG,
  APPEND_LOG,
  LOG_UPDATED,
  THEME_PROGRESS,
  SELECT_NODE,
  FILE_NAME,
  GET_FILE_NAME,
  GET_LOCAL_VARIABLES,
  LOCAL_VARIABLES,
  SEARCH_NODES_WITH_VARIABLE,
  NODES_WITH_VARIABLE,
  APPLY_ACCENT_STYLING,
  CLEAR_ACCENT_STYLING,
  ACCENT_STYLING_APPLIED,
};
